Update 0-run

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,16 @@
 #!/bin/bash
-python3 $PYFILE
+
+# Check if the $PYFILE environment variable is set
+if [[ -z "$PYFILE" ]]; then
+  echo "Error: The \$PYFILE environment variable is not set."
+  exit 1
+fi
+
+# Check if the Python file exists
+if [[ ! -f "$PYFILE" ]]; then
+  echo "Error: Python file '$PYFILE' does not exist."
+  exit 1
+fi
+
+# Run the Python script
+python "$PYFILE"
